
services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb
    restart: always
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception

  wordpress:
    build: ./requirements/wordpress
    env_file:
      - .env
    volumes:
      - wp_data:/var/www/html
    networks:
      - inception
    depends_on:
      - mariadb

  nginx:
    build: ./requirements/nginx
    env_file:
      - .env
    ports:
      - "443:443"
    volumes:
      - wp_data:/var/www/html # 동일한 볼륨 마운트
    networks:
      - inception
    depends_on:
      - wordpress

# 만약 과제에서 호스트 경로 지정을 요구한다면 아래 설정을 수정해야 합니다.
volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/chanypar/data/mariadb
  wp_data: # 여기에 추가!
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/chanypar/data/wordpress

networks:
  inception:
    driver: bridge