server {
    listen 443 ssl;
    server_name chanypar.42.fr;

    root /var/www/html;
    index index.php index.html;

    # SSL 설정 (과제 필수)
    ssl_certificate /etc/nginx/ssl/chanypar.crt;
    ssl_certificate_key /etc/nginx/ssl/chanypar.key;
    ssl_protocols TLSv1.2 TLSv1.3;

    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    # PHP 요청 처리 (핵심!)
    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        # wordpress는 docker-compose에 정의된 서비스 이름입니다.
        fastcgi_pass wordpress:9000; 
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }
}